zhonglewang/apps/accounts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^register/$',views.Register.as_view(),name="register"),
    url(r'^login/$',views.Login.as_view(),name="login"),
    url(r'^logout/$',views.logout,name="logout"),
]

zhonglewang/apps/apis/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    # 获取手机验证码
    url(r'^mobile_captcha/$',views.mobile_captcha,name="mobile_captcha"),
    # 获取文章
    url(r'^articles/$', views.ArticlesView.as_view(), name="articles"),
    # 收藏文章
    url(r'^article/collection/(?P<id>\d+)/$', views.ArticleCollectionView.as_view(), name='question_collection'),


]

zhonglewang/apps/tasks/urls.py
from django.conf.urls import url
from django.views import View
from . import views

urlpatterns = [
    url(r'^freelist/$',views.freelist,name="freelist"),
    url(r'^securitylist/$',views.securitylist,name="securitylist"),
    url(r'^create/$',views.TaskCreate.as_view(),name="create"),
    url(r'^free_detail/(?P<id>\d+)/$',views.free_detail,name="free_detail"),
    url(r'^security_detail/(?P<id>\d+)/$',views.security_detail,name="security_detail"),
]

zhonglewang/apps/techstack/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    # 展示所有文章
    url(r'^articles/$',views.ArticlesList.as_view(),name="articles"),
    # 测试
    url(r'article/$', views.test, name="article"),
    # 展示文章详情
    url(r'^article/(?P<id>\d+)/$', views.article_detail,name="article_detail"),
    # 发表文章
    url(r'^article_create/$',views.ArticleCreate.as_view(),name="article_create"),
    # 删除文章
    url(r'^article_delete/(?P<id>\d+)$',views.article_delete,name="article_delete"),
    # 修改文章
    url(r'^article_update/(?P<id>\d+)',views.ArticleUpdate.as_view(),name="article_update")

]

zhonglewang/zhonglewang/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
from django.views.static import serve
from .settings import MEDIA_ROOT

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name="index"),
    url(r'^accounts/',include('apps.accounts.urls',namespace="accounts")),
    url(r'^apis/',include('apps.apis.urls',namespace="apis")),
    url(r'^techstack/',include('apps.techstack.urls',namespace="techstack")),
    url(r'^tasks/',include('apps.tasks.urls',namespace="tasks")),
    url(r'^usercenter/',include('apps.usercenter.urls',namespace="usercenter")),
    # meida 处理
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    # ckeditor
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    # chat
    url(r'^chat/',include("apps.chat.urls",namespace="chat")),
]

zhonglewang/templates/article_create.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    发表文章
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="title">文章标题</label>
                        <input type="text" class="form-control" id="title" name="title">
                    </div>
                    <div class="form-group">
                        <label for="body">文章正文</label>
                        <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">完成</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block scr %}
    <script src="{% static 'layui/layui.js' %}"></script>
{#    <script href="{% static 'layui/lay/modules/layedit.js' %}"></script>#}
    {# layui富文本编辑器 #}
    <script>
        layui.use('layedit',function () {
            var layedit = layui.layedit;
            // 建立编辑器
            layedit.build('body');
        })
    </script>
{% endblock %}
{% block load_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'layui/css/layui.css' %}">
{% endblock %}

zhonglewang/templates/article_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    文章详情
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <h1 class="col-12 mt-4 mb-4">{{ article.title }}</h1>
            <div class="col-12 alert alert-success">
                作者：{{ user }}
                {% if user == article.author %}
                ···<a href="#" onclick="confirm_delete()">删除文章</a>···
                <a href="{% url 'techstack:article_update' article.id %}">编辑文章</a>···
                {% endif %}
                <div>
                浏览量：{{ article.total_views }}
                </div>
            </div>
            <div class="col-12">
                {{ article.body|safe }}
{#                <p>{{ article.body }}</p>#}
            </div>
        </div>
    </div>
{% endblock %}
{% block scr %}
    {# 引入layer.js #}
    <script src="{% static 'layer/layer.js' %}"></script>
    <script>
        //删除文章函数
        function confirm_delete() {
            // 调用layer组件
            layer.open({
                // 弹窗标题
                title:"确认删除",
                content:"是否确认删除这边文章？",
                yes:function (index,layero) {
                    // 指定应当前往的url
                    location.href='{% url 'techstack:article_delete' article.id %}'
                }
            })
        }
    </script>
{% endblock %}
{% block load_css %}
{% endblock %}

zhonglewang/templates/article_update.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    修改文章
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="title">文章标题</label>
                        <input type="text" class="form-control" id="title" name="title">
                    </div>
                    <div class="form-group">
                        <label for="body">文章正文</label>
                        <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">完成</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block scr %}
    {# layui富文本编辑器 #}
    <script src="{% static 'js/layedit.js' %}"></script>
    <script>
        layui.use('layedit',function () {
            var layedit = layui.layedit;
            // 建立编辑器
            layedit.build('body');
        })
    </script>
{% endblock %}

zhonglewang/templates/chat_index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br/>
    <input id="room-name-input" type="text" size="100"/><br/>
    <input id="room-name-submit" type="button" value="Enter"/>

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
</body>
</html>

zhonglewang/templates/chat_room.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
    <textarea id="chat-log" cols="100" rows="20"></textarea><br/>
    <input id="chat-message-input" type="text" size="100"/><br/>
    <input id="chat-message-submit" type="button" value="Send"/>
</body>
<script>
    var roomName = {{ room_name_json }};

    var chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/chat/' + roomName + '/');

    chatSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        var message = data['message'];
        document.querySelector('#chat-log').value += (message + '\n');
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
        var messageInputDom = document.querySelector('#chat-message-input');
        var message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'message': message
        }));

        messageInputDom.value = '';
    };
</script>
</html>

zhonglewang/templates/login.html
{% extends 'base.html' %}
{% block title %}
    用户登录
{% endblock %}
{% block content %}
<div class="p-box">
    	<div class="content ct-login">
    		<h1>众乐网-登录</h1>
    		<form method="post">
                {% csrf_token %}
	    		<div class="login">
	    			<div class="filter">
	    				{{ form.username }}
	    			</div>
	    			<div class="filter">
	    				{{ form.password }}
	    			</div>
	    			<div class="filter">
	    				<input type="submit" class="btn-login" value="登录">
	    			</div>
	    			<div class="filter">
	    				<div  class="f-pwd">
	    					<a href="">忘记密码？</a>
	    				</div>
	    			</div>
                    <p class="msg"></p>
                    {% if msg %}
                    <div class="alert alert-block alert-danger fade in">
                          <button data-dismiss="alert" class="close close-sm" type="button">
                              <i class="icon-remove"></i>
                          </button>
                          <strong>提醒!</strong> {{ msg }}
                    </div>
                    {% endif %}
	    		</div>
	    	</form>
    	</div>
    </div>
{% endblock %}
{% block src %}
    <script>
        $(function(){
            $(".nav li").hover(function() {
                $(".second-nav",this).slideDown(100);
                /* Stuff to do when the mouse enters the element */
            }, function() {
                $(".second-nav",this).slideUp(100);
                // $(".second-nav").hide();
                /* Stuff to do when the mouse leaves the element */
            });
            $(".login label").click(function(){
                $(this).next().focus();
            });
            $(".login input").blur(function(event) {
                if ($(this).val()=="") {
                    $(this).prev().show();
                };
                /* Act on the event */
            });
            $(".login input").focus(function(event) {
                $(this).prev().hide();
                /* Act on the event */
            });
            $(".login input.username").blur(function(event) {
                if ($(this).val()=="") {
                    $(this).next().show().text("请输入用户名");
                }
                else{
                    $(this).next().hide();
                }
                /* Act on the event */
            });
        })
    </script>
{% endblock src %}

zhonglewang/templates/register.html
{% extends 'base.html' %}
{% block title %}
    用户注册
{% endblock %}
{% block content %}
<div class="p-box">
    	<div class="content" style="margin:97px auto;">
    		<h1>新用户注册</h1>
    		<form method="post" id="register_form">
                {% csrf_token %}
	    		<div class="login">
	    			<div class="filter">
	    				{{ form.username }}
	    				<div class="validate">
	    					邮箱不能为空
	    				</div>
	    			</div>
	    			<div class="filter">
	    				{{ form.password }}
	    			</div>
	    			<div class="filter">
	    				{{ form.password2 }}
	    			</div>
	    			<div class="filter">
	    				{{ form.mobile }}
	    			</div>
	    			<div class="filter">
	    				{{ form.mobile_captcha }}
{#	    				<a href="" style="" class="telvalidate">获取手机验证码</a>#}
                        {# 给发送短信按钮添加动作 #}
                        <a onclick="sendmessage(this,60);" type="button" class="telvalidate">获取手机验证码</a>
	    			</div>
	    			<div class="filter">
                        <input type="button" class="btn-login" value="注册" id="register_btn">
	    			</div>
	    			<div class="filter">
	    				<div class="f-pwd">
	    					已有账号？<a href="{% url 'accounts:login' %}">马上登录</a>
	    				</div>
	    			</div>
	    		</div>
	    	</form>
    	</div>
    </div>
{% endblock %}
{% block scr %}
    <script>
        $(function(){
            $(".nav li").hover(function() {
                $(".second-nav",this).slideDown(100);
                /* Stuff to do when the mouse enters the element */
            }, function() {
                $(".second-nav",this).slideUp(100);
                // $(".second-nav").hide();
                /* Stuff to do when the mouse leaves the element */
            });
            $(".login label").click(function(){
                $(this).next().focus();
            });
            $(".login input").blur(function(event) {
                if ($(this).val()=="") {
                    $(this).prev().show();
                };
                /* Act on the event */
            });
            $(".login input").focus(function(event) {
                $(this).prev().hide();
                /* Act on the event */
            });
        });
        {# 发送短信验证码 #}
        function sendmessage(obj,second){
            var telRegex = /(13|14|15|17|18)\d{9}/;
            if(telRegex.test($.trim($("#id_mobile").val()))){
                $.ajax({
                    url: "{% url 'apis:mobile_captcha' %}",
                    type: "GET",
                    dataType: "json",
                    data: {"mobile": $("#id_mobile").val()},
                    success: function (data) {
                         $.gritter.add({
                            // (string | mandatory) the heading of the notification
                            title: '提交结果',
                            // (string | mandatory) the text inside the notification
                          //text: 'This will fade out after a certain amount of time. Vivamus eget tincidunt velit. Cum sociis natoque penatibus et <a href="#" style="color:#ccc">magnis dis parturient</a> montes, nascetur ridiculus mus.'
                            text: data.msg
                        });
                    }
                });
                countDown(obj,second)
            } else{
                $.gritter.add({
                    // (string | mandatory) the heading of the notification
                    title: '提交结果',
                    // (string | mandatory) the text inside the notification
                    //text: 'This will fade out after a certain amount of time. Vivamus eget tincidunt velit. Cum sociis natoque penatibus et <a href="#" style="color:#ccc">magnis dis parturient</a> montes, nascetur ridiculus mus.'
                    text: '手机号有误'
                });
            }
        }

        {# 重新发送倒计时 #}
        function countDown(obj,second){
        // 如果秒数还是大于0，则表示倒计时还没结束
         if(second>=0){
              // 获取默认按钮上的文字
              if(typeof buttonDefaultValue === 'undefined' ){
                buttonDefaultValue =  obj.defaultValue;
            }
            // 按钮置为不可点击状态
            obj.disabled = true;
            // 按钮里的内容呈现倒计时状态
            obj.value = buttonDefaultValue+'('+second+')';
            // 时间减一
            second--;
            // 一秒后重复执行
            setTimeout(function(){countDown(obj,second);},1000);
            // 否则，按钮重置为初始状态
            }else{
            // 按钮置未可点击状态
            obj.disabled = false;
            // 按钮里的内容恢复初始状态
            obj.value = buttonDefaultValue;
           }
        }
        {# ajax动态检查验证码 #}
        $("#register_btn").click(function () {
            // some_check
            $.ajax({
                url: "{% url 'accounts:register' %}",
                type: "POST",
                dataType: "json",
                data: $("#register_form").serialize(),
                success: function (data) {
                    if(data.status == 200 ){
                        window.location.href='{% url 'index' %}';
                    }else{
                        msg = "新错误类型"
                        if(data.status == 400 || data.status == 401){
                            msg = data.msg
                        }else{
                            for(var i in data.msg){
                                msg = i+data.msg[i]
                                break
                            }
                        }
                         $.gritter.add({
                            // (string | mandatory) the heading of the notification
                            title: '提交结果',
                            // (string | mandatory) the text inside the notification
                            //text: 'This will fade out after a certain amount of time. Vivamus eget tincidunt velit. Cum sociis natoque penatibus et <a href="#" style="color:#ccc">magnis dis parturient</a> montes, nascetur ridiculus mus.'
                            text: msg
                        });
                     }
                },
                // 解决csrftoken
                beforeSend: function(xhr, settings) {
                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                }
            });
        });
    </script>
{% endblock %}

zhonglewang/templates/task_freelist.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    任务大厅-自由模式
{% endblock %}
{% block content %}
    <div style="margin-top: 30px">
        &nbsp&nbsp&nbsp
        <i class="glyphicon glyphicon-bell" style="color: #0c80ba"></i>
        当前位置：任务大厅&nbsp-->&nbsp;自由模式任务列表
    </div>
    <div class="alert alert-info" role="alert" style="margin-top: 20px;line-height: 7px;font-size: 12px">
        <i class="glyphicon glyphicon-exclamation-sign"></i>
        自由模式：任务自由化，所有的沟通均由双方线下沟通，酬劳直接扫码到账，方便，快捷，效率高。此模式需求双方彼此信任，对个人素质要求极高，推荐低酬劳任务和紧急任务。
    </div>
    <div>
        <ol class="breadcrumb" style="background-color: #ffffff">
          <li>
              <i class="glyphicon glyphicon-random" style="color: #0c80ba"></i>
              <a href="{% url 'tasks:freelist' %}">自由模式</a>
          </li>
          <li>
              <i class="glyphicon glyphicon-user" style="color: #0c80ba"></i>
              <a href="{% url 'tasks:securitylist' %}">担保模式</a>
          </li>
        </ol>
    </div>
    <div class="container" style="margin-top: 30px">
        {# 任务排序方式选择开始 #}
        <div class="row">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{% url 'tasks:freelist' %}?search={{ search }}">
                            最新
                        </a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="{% url 'tasks:freelist' %}?order=total_views&search={{ search }}">
                            最热
                        </a>
                    </li>
                </ol>
            </nav>
        </div>
        {# 任务排序方式选择结束 #}

        {# 搜索栏开始 #}
        <div class="row">
            <div class="col-lg-4" style="float: right">
                <form class="form-inline">
                    <label class="sr-only">content</label>
                    <input type="text" class="form-control mb-2 mr-sm-2" name="search" placeholder="search" value="{{ search }}">
                </form>
            </div>
        </div>
        {# 搜索栏结束 #}

        {# 任务列表开始mt-2 #}
        <div class="row">
            {% for task in tasks_free %}
                {# 标题图 #}
                {% if task.avatar %}
                    <div class="col-3" style="float: left;margin-right: 20px">
                        <img src="{{ task.avatar.url }}" alt="avatar" style="max-width: 100%;border-radius: 20px">
                    </div>
                {% endif %}
                {# 任务内容 #}
                <div class="col">
                    {# 类别 #}
                    {% if task.category %}
                        <button type="button"
                            class="btn btn-sm mb-2
                                {% if task.category.name == 'Django' %}
                                    btn-success
                                {% elif task.category.name == 'Python' %}
                                    btn-danger
                                {% elif task.category.name == 'HTML' %}
                                    btn-warning
                                {% else %}
                                    btn-primary
                                {% endif %}
                            "
                        >
                            {{ task.category }}
                        </button>
                    {% endif %}
                    {# 酬劳 #}
                    <span>
                        <button class="btn btn-sm mb-2 btn-info">{{ task.reward }}元</button>
                    </span>
                    {# 标签 #}
                    <span>
                        {% for tag in task.tags.all %}
                            <a href="#" class="badge badge-light">{{ tag }}</a>
                        {% endfor %}
                    </span>
                    {# 标题 #}
                    <h4>
                        <b>
                            <a href="{% url 'tasks:freelist' %}" style="color: black">
                                {{ task.title }}
                            </a>
                        </b>
                    </h4>
                    {# 内容摘要 #}
                    <div>
                        <p style="color: grey">
                            {{ task.content|safe|slice:"100" }}...
                        </p>
                    </div>
                    {# 附加信息 #}
                    <p>
                        <span style="color: green">
                            {{ task.total_views }}浏览 &nbsp;&nbsp;&nbsp;
                        </span>
                        <span style="color: blue">
                            {{ task.created|date:'Y-m-d' }}发布 &nbsp;&nbsp;&nbsp;
                        </span>
                        <span style="color: darkred">
                            {{ task.updated|date:'Y-m-d' }}更新
                        </span>
                        <span style="float: right">
                            <a type="button" class="btn btn-primary" href="{% url 'tasks:free_detail' task.id%}">
                                查看详情
                            </a>
                        </span>
                    </p>
                </div>
                <hr style="width: 100%"/>
            {% endfor %}
        </div>
        {# 任务列表结束 #}
    {# 页码导航 #}
    <div class="pagination row" style="margin-left: 500px">
        <div class="m-auto">
            <span class="step-links">
                {# 如果不是上一页，则显示上翻按钮 #}
                {% if tasks_free.has_previous %}
                    <a href="?page=1&order={{ order }}&search={{ search }}" class="btn btn-success">
                        &laquo;1
                    </a>
                    <span>...</span>
                    <a href="?page={{ tasks_free.previous_page_number }}&order={{ order }}&search={{ search }}" class="btn btn-secondary">
                        {{ tasks_free.previous_page_number }}
                    </a>
                {% endif %}
                {# 当前页面 #}
                <span class="current btn btn-danger btn-lg">
                    {{ tasks_free.number }}
                </span>
                {# 如果不是最后一页，则显示下翻按钮 #}
                {% if tasks_free.has_next %}
                    <a href="?page={{ tasks_free.next_page_number }}&order={{ order }}&search={{ search }}" class="btn btn-secondary">
                        {{ tasks_free.next_page_number }}
                    </a>
                    <span>...</span>
                    <a href="?page={{ tasks_free.paginator.num_pages }}&order={{ order }}&search={{ search }}" class="btn btn-success">
                        {{ tasks_free.paginator.num_pages }}&raquo;
                    </a>
                {% endif %}
            </span>
        </div>
    </div>
{% endblock %}

{% block scr %}

{% endblock %}

{% block load_css %}
{% endblock %}

zhonglewang/templates/task_securitylist.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    任务大厅-担保模式
{% endblock %}
{% block content %}
    <div style="margin-top: 30px">
        &nbsp&nbsp&nbsp
        <i class="glyphicon glyphicon-bell" style="color: #0c80ba"></i>
        当前位置：任务大厅&nbsp-->&nbsp担保模式任务列表
    </div>
    <div class="alert alert-info" role="alert" style="margin-top: 20px;line-height: 7px;font-size: 12px">
        <i class="glyphicon glyphicon-exclamation-sign"></i>
        担保模式：发布任务需要提前支付酬劳到平台，平台收取10%的保障金。此模式安全有保障。但是效率和灵活度相比较自由模式不足。
    </div>
    <div>
        <ol class="breadcrumb" style="background-color: #ffffff">
          <li>
              <i class="glyphicon glyphicon-random" style="color: #0c80ba"></i>
              <a href="{% url 'tasks:freelist' %}">自由模式</a>
          </li>
          <li>
              <i class="glyphicon glyphicon-user" style="color: #0c80ba"></i>
              <a href="{% url 'tasks:securitylist' %}">担保模式</a>
          </li>
        </ol>
    </div>
    <div class="container" style="margin-top: 30px">
        {# 任务排序方式选择开始 #}
        <div class="row">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{% url 'tasks:securitylist' %}?search={{ search }}">
                            最新
                        </a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="{% url 'tasks:securitylist' %}?order=total_views&search={{ search }}">
                            最热
                        </a>
                    </li>
                </ol>
            </nav>
        </div>
        {# 任务排序方式选择结束 #}
        {# 搜索栏开始 #}
        <div class="row">
            <div class="col-lg-4" style="float: right">
                <form class="form-inline">
                    <label class="sr-only">content</label>
                    <input type="text" class="form-control mb-2 mr-sm-2" name="search" placeholder="search" value="{{ search }}">
                </form>
            </div>
        </div>
        {# 搜索栏结束 #}
        {# 任务列表开始 #}
        <div class="row mt-2">
            {% for task in tasks_security %}
                {# 任务内容 #}
                {# 标题图 #}
                {% if task.avatar %}
                    <div class="col-3" style="float: left;margin-right: 20px">
                        <img src="{{ task.avatar.url }}" alt="avatar" style="max-width: 100%;border-radius: 20px">
                    </div>
                {% endif %}
                <div class="col-12">
                    {# 类别 #}
                    {% if task.category %}
                        <button type="button"
                            class="btn btn-sm mb-2
                                {% if task.category.name == 'Django' %}
                                    btn-success
                                {% elif task.category.name == 'Python' %}
                                    btn-danger
                                {% elif task.category.name == 'HTML' %}
                                    btn-warning
                                {% else %}
                                    btn-primary
                                {% endif %}
                            "
                        >
                            {{ task.category }}
                        </button>
                    {% endif %}
                    {# 酬劳 #}
                    <span>
                        <button class="btn btn-sm mb-2 btn-info">{{ task.reward }}元</button>
                    </span>
                    {# 标签 #}
                    <span>
                        {% for tag in task.tags.all %}
                            <a href="#" class="badge badge-light">{{ tag }}</a>
                        {% endfor %}
                    </span>
                    {# 标题 #}
                    <h4>
                        <b>
                            <a href="{% url 'tasks:freelist' %}" style="color: black">
                                {{ task.title }}
                            </a>
                        </b>
                    </h4>
                    {# 内容摘要 #}
                    <div>
                        <p style="color: grey">
                            {{ task.content|safe|slice:"100" }}...
                        </p>
                    </div>
                    {# 附加信息 #}
                    <p>
                        <span style="color: green">
                            {{ task.total_views }}浏览 &nbsp;&nbsp;&nbsp;
                        </span>
                        <span style="color: blue">
                            {{ task.created|date:'Y-m-d' }}发布 &nbsp;&nbsp;&nbsp;
                        </span>
                        <span style="color: darkred">
                            {{ task.updated|date:'Y-m-d' }}更新
                        </span>
                        <span style="float: right">
                            <a type="button" class="btn btn-primary" href="{% url 'tasks:security_detail' task.id%}">
                                查看详情
                            </a>
                        </span>
                    </p>
                    <hr>
                </div>
            {% endfor %}
        </div>
        {# 任务列表结束 #}
    </div>
    {# 页码导航开始 #}
    <div class="pagination row" style="margin-left: 500px">
        <div class="m-auto">
            <span class="step-links">
                {# 如果不是第一页，则显示上翻按钮 #}
                {% if tasks_security.has_previous %}
                    <a href="?page=1&order={{ order }}&search={{ search }}" class="btn btn-success">
                        &laquo;1
                    </a>
                    <span>...</span>
                    <a href="?page={{ tasks_security.previous_page_number }}&order={{ order }}&search={{ search }}" class="btn btn-secondary">
                        {{ tasks_security.previous_page_number }}
                    </a>
                {% endif %}
                {# 当前页面 #}
                <span class="current btn btn-danger btn-lg">
                    {{ tasks_security.number }}
                </span>
                {# 如果不是最后一页，则显示下翻按钮 #}
                {% if tasks_security.has_next %}
                    <a href="?page={{ tasks_security.next_page_number }}&order={{ order }}&search={{ search }}" class="btn btn-secondary">
                        {{ tasks_security.next_page_number }}
                    </a>
                    <span>...</span>
                    <a href="?page={{ tasks_security.paginator.num_pages }}&order={{ order }}&search={{ search }}" class="btn btn-success">
                        {{ tasks_security.paginator.num_pages }}&raquo;
                    </a>
                {% endif %}
            </span>
        </div>
    </div>
    {# 页码导航结束 #}
{% endblock %}

{% block scr %}

{% endblock %}

{% block load_css %}
{% endblock %}